// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/central/proto/central.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Metadata for a Check.
type Check struct {
	Input                *Check_Component   `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	Target               *Check_Component   `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Output               *Check_Component   `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	Payloads             []*Check_Component `protobuf:"bytes,4,rep,name=payloads,proto3" json:"payloads,omitempty"`
	Interval             int64              `protobuf:"varint,5,opt,name=interval,proto3" json:"interval,omitempty"`
	Timeout              int64              `protobuf:"varint,6,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Name                 string             `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Id                   uint32             `protobuf:"varint,8,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Check) Reset()         { *m = Check{} }
func (m *Check) String() string { return proto.CompactTextString(m) }
func (*Check) ProtoMessage()    {}
func (*Check) Descriptor() ([]byte, []int) {
	return fileDescriptor_3899a1d80cfff707, []int{0}
}

func (m *Check) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Check.Unmarshal(m, b)
}
func (m *Check) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Check.Marshal(b, m, deterministic)
}
func (m *Check) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Check.Merge(m, src)
}
func (m *Check) XXX_Size() int {
	return xxx_messageInfo_Check.Size(m)
}
func (m *Check) XXX_DiscardUnknown() {
	xxx_messageInfo_Check.DiscardUnknown(m)
}

var xxx_messageInfo_Check proto.InternalMessageInfo

func (m *Check) GetInput() *Check_Component {
	if m != nil {
		return m.Input
	}
	return nil
}

func (m *Check) GetTarget() *Check_Component {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *Check) GetOutput() *Check_Component {
	if m != nil {
		return m.Output
	}
	return nil
}

func (m *Check) GetPayloads() []*Check_Component {
	if m != nil {
		return m.Payloads
	}
	return nil
}

func (m *Check) GetInterval() int64 {
	if m != nil {
		return m.Interval
	}
	return 0
}

func (m *Check) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *Check) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Check) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

// Each component of a check has two things associated with it.
// First the type of the value and second the value of the component.
type Check_Component struct {
	Type                 string   `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Check_Component) Reset()         { *m = Check_Component{} }
func (m *Check_Component) String() string { return proto.CompactTextString(m) }
func (*Check_Component) ProtoMessage()    {}
func (*Check_Component) Descriptor() ([]byte, []int) {
	return fileDescriptor_3899a1d80cfff707, []int{0, 0}
}

func (m *Check_Component) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Check_Component.Unmarshal(m, b)
}
func (m *Check_Component) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Check_Component.Marshal(b, m, deterministic)
}
func (m *Check_Component) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Check_Component.Merge(m, src)
}
func (m *Check_Component) XXX_Size() int {
	return xxx_messageInfo_Check_Component.Size(m)
}
func (m *Check_Component) XXX_DiscardUnknown() {
	xxx_messageInfo_Check_Component.DiscardUnknown(m)
}

var xxx_messageInfo_Check_Component proto.InternalMessageInfo

func (m *Check_Component) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Check_Component) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type PushStatus struct {
	Pushed               bool     `protobuf:"varint,1,opt,name=Pushed,proto3" json:"Pushed,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=Reason,proto3" json:"Reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushStatus) Reset()         { *m = PushStatus{} }
func (m *PushStatus) String() string { return proto.CompactTextString(m) }
func (*PushStatus) ProtoMessage()    {}
func (*PushStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_3899a1d80cfff707, []int{1}
}

func (m *PushStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushStatus.Unmarshal(m, b)
}
func (m *PushStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushStatus.Marshal(b, m, deterministic)
}
func (m *PushStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushStatus.Merge(m, src)
}
func (m *PushStatus) XXX_Size() int {
	return xxx_messageInfo_PushStatus.Size(m)
}
func (m *PushStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_PushStatus.DiscardUnknown(m)
}

var xxx_messageInfo_PushStatus proto.InternalMessageInfo

func (m *PushStatus) GetPushed() bool {
	if m != nil {
		return m.Pushed
	}
	return false
}

func (m *PushStatus) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type RemoveStatus struct {
	Removed              bool     `protobuf:"varint,1,opt,name=Removed,proto3" json:"Removed,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=Reason,proto3" json:"Reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveStatus) Reset()         { *m = RemoveStatus{} }
func (m *RemoveStatus) String() string { return proto.CompactTextString(m) }
func (*RemoveStatus) ProtoMessage()    {}
func (*RemoveStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_3899a1d80cfff707, []int{2}
}

func (m *RemoveStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveStatus.Unmarshal(m, b)
}
func (m *RemoveStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveStatus.Marshal(b, m, deterministic)
}
func (m *RemoveStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveStatus.Merge(m, src)
}
func (m *RemoveStatus) XXX_Size() int {
	return xxx_messageInfo_RemoveStatus.Size(m)
}
func (m *RemoveStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveStatus.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveStatus proto.InternalMessageInfo

func (m *RemoveStatus) GetRemoved() bool {
	if m != nil {
		return m.Removed
	}
	return false
}

func (m *RemoveStatus) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type CheckMeta struct {
	ID                   uint32   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckMeta) Reset()         { *m = CheckMeta{} }
func (m *CheckMeta) String() string { return proto.CompactTextString(m) }
func (*CheckMeta) ProtoMessage()    {}
func (*CheckMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_3899a1d80cfff707, []int{3}
}

func (m *CheckMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckMeta.Unmarshal(m, b)
}
func (m *CheckMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckMeta.Marshal(b, m, deterministic)
}
func (m *CheckMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckMeta.Merge(m, src)
}
func (m *CheckMeta) XXX_Size() int {
	return xxx_messageInfo_CheckMeta.Size(m)
}
func (m *CheckMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckMeta.DiscardUnknown(m)
}

var xxx_messageInfo_CheckMeta proto.InternalMessageInfo

func (m *CheckMeta) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func init() {
	proto.RegisterType((*Check)(nil), "proto.Check")
	proto.RegisterType((*Check_Component)(nil), "proto.Check.Component")
	proto.RegisterType((*PushStatus)(nil), "proto.PushStatus")
	proto.RegisterType((*RemoveStatus)(nil), "proto.RemoveStatus")
	proto.RegisterType((*CheckMeta)(nil), "proto.CheckMeta")
}

func init() { proto.RegisterFile("api/central/proto/central.proto", fileDescriptor_3899a1d80cfff707) }

var fileDescriptor_3899a1d80cfff707 = []byte{
	// 365 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x4f, 0x6f, 0xa3, 0x30,
	0x10, 0xc5, 0x03, 0x09, 0x04, 0x26, 0x7f, 0xb4, 0xeb, 0x5d, 0x45, 0x16, 0x7b, 0x58, 0xc4, 0x89,
	0xc3, 0x8a, 0x48, 0x59, 0xb5, 0xa7, 0x1e, 0x2a, 0x25, 0x97, 0x1c, 0x2a, 0x55, 0x4e, 0xd5, 0xbb,
	0x1b, 0x46, 0x0d, 0x2a, 0x60, 0x04, 0x26, 0x6a, 0xbe, 0x6a, 0x3f, 0x4d, 0x65, 0x1b, 0xd2, 0x5c,
	0x9a, 0x93, 0xfd, 0x1b, 0xbf, 0x37, 0xf6, 0x3c, 0x19, 0xfe, 0xf2, 0x2a, 0x5b, 0xee, 0xb1, 0x94,
	0x35, 0xcf, 0x97, 0x55, 0x2d, 0xa4, 0xe8, 0x29, 0xd1, 0x44, 0x1c, 0xbd, 0x44, 0x1f, 0x36, 0x38,
	0xeb, 0x03, 0xee, 0xdf, 0xc8, 0x3f, 0x70, 0xb2, 0xb2, 0x6a, 0x25, 0xb5, 0x42, 0x2b, 0x9e, 0xac,
	0x16, 0x46, 0x97, 0xe8, 0xc3, 0x64, 0x2d, 0x8a, 0x4a, 0x94, 0x58, 0x4a, 0x66, 0x44, 0x24, 0x01,
	0x57, 0xf2, 0xfa, 0x15, 0x25, 0xb5, 0xaf, 0xca, 0x3b, 0x95, 0xd2, 0x8b, 0x56, 0xaa, 0xf6, 0xc3,
	0xeb, 0x7a, 0xa3, 0x22, 0x2b, 0xf0, 0x2a, 0x7e, 0xca, 0x05, 0x4f, 0x1b, 0x3a, 0x0a, 0x87, 0x57,
	0x1c, 0x67, 0x1d, 0x09, 0xc0, 0xcb, 0x4a, 0x89, 0xf5, 0x91, 0xe7, 0xd4, 0x09, 0xad, 0x78, 0xc8,
	0xce, 0x4c, 0x28, 0x8c, 0x65, 0x56, 0xa0, 0x68, 0x25, 0x75, 0xf5, 0x51, 0x8f, 0x84, 0xc0, 0xa8,
	0xe4, 0x05, 0xd2, 0x71, 0x68, 0xc5, 0x3e, 0xd3, 0x7b, 0x32, 0x07, 0x3b, 0x4b, 0xa9, 0x17, 0x5a,
	0xf1, 0x8c, 0xd9, 0x59, 0x1a, 0xdc, 0x80, 0x7f, 0xbe, 0x50, 0x19, 0x9e, 0x4e, 0x15, 0xea, 0x9c,
	0x7c, 0xa6, 0xf7, 0xe4, 0x37, 0x38, 0xcf, 0x3c, 0x6f, 0x51, 0xa7, 0xe1, 0x33, 0x03, 0xd1, 0x1d,
	0xc0, 0x63, 0xdb, 0x1c, 0x76, 0x92, 0xcb, 0xb6, 0x21, 0x0b, 0x70, 0x15, 0x61, 0xaa, 0x9d, 0x1e,
	0xeb, 0x48, 0xd5, 0x19, 0xf2, 0x46, 0x94, 0x9d, 0xb9, 0xa3, 0xe8, 0x1e, 0xa6, 0x0c, 0x0b, 0x71,
	0xc4, 0xce, 0x4f, 0x61, 0x6c, 0xb8, 0x6f, 0xd0, 0xe3, 0xb7, 0x1d, 0xfe, 0x80, 0xaf, 0xd3, 0x7a,
	0x40, 0xc9, 0xd5, 0x4c, 0xdb, 0x8d, 0x76, 0xce, 0x98, 0xbd, 0xdd, 0xac, 0xde, 0x61, 0xbe, 0x36,
	0x3f, 0x62, 0x87, 0xf5, 0x31, 0xdb, 0x23, 0x49, 0xc0, 0x57, 0x4f, 0x32, 0xdf, 0x61, 0x7a, 0x19,
	0x77, 0xf0, 0xb3, 0xa3, 0xaf, 0x71, 0xa2, 0x01, 0xb9, 0x85, 0x89, 0x79, 0x81, 0x71, 0xfc, 0xb8,
	0x74, 0xa8, 0x2b, 0x83, 0x5f, 0x5d, 0xe5, 0x72, 0x8c, 0x68, 0xf0, 0xe2, 0xea, 0xea, 0xff, 0xcf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x05, 0x14, 0x0a, 0x54, 0xa4, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CentralServiceClient is the client API for CentralService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CentralServiceClient interface {
	// Pushes a check to the central service to be further assigned to a registered agent.
	PushCheck(ctx context.Context, in *Check, opts ...grpc.CallOption) (*PushStatus, error)
	// Removes a check from the manager managing the controller for the checks.
	// Only reuired filed for the CheckMeta is `ID` rest everything can be ignored.
	RemoveCheck(ctx context.Context, in *CheckMeta, opts ...grpc.CallOption) (*RemoveStatus, error)
}

type centralServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCentralServiceClient(cc grpc.ClientConnInterface) CentralServiceClient {
	return &centralServiceClient{cc}
}

func (c *centralServiceClient) PushCheck(ctx context.Context, in *Check, opts ...grpc.CallOption) (*PushStatus, error) {
	out := new(PushStatus)
	err := c.cc.Invoke(ctx, "/proto.CentralService/PushCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *centralServiceClient) RemoveCheck(ctx context.Context, in *CheckMeta, opts ...grpc.CallOption) (*RemoveStatus, error) {
	out := new(RemoveStatus)
	err := c.cc.Invoke(ctx, "/proto.CentralService/RemoveCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CentralServiceServer is the server API for CentralService service.
type CentralServiceServer interface {
	// Pushes a check to the central service to be further assigned to a registered agent.
	PushCheck(context.Context, *Check) (*PushStatus, error)
	// Removes a check from the manager managing the controller for the checks.
	// Only reuired filed for the CheckMeta is `ID` rest everything can be ignored.
	RemoveCheck(context.Context, *CheckMeta) (*RemoveStatus, error)
}

// UnimplementedCentralServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCentralServiceServer struct {
}

func (*UnimplementedCentralServiceServer) PushCheck(ctx context.Context, req *Check) (*PushStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushCheck not implemented")
}
func (*UnimplementedCentralServiceServer) RemoveCheck(ctx context.Context, req *CheckMeta) (*RemoveStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveCheck not implemented")
}

func RegisterCentralServiceServer(s *grpc.Server, srv CentralServiceServer) {
	s.RegisterService(&_CentralService_serviceDesc, srv)
}

func _CentralService_PushCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Check)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CentralServiceServer).PushCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CentralService/PushCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CentralServiceServer).PushCheck(ctx, req.(*Check))
	}
	return interceptor(ctx, in, info, handler)
}

func _CentralService_RemoveCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckMeta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CentralServiceServer).RemoveCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CentralService/RemoveCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CentralServiceServer).RemoveCheck(ctx, req.(*CheckMeta))
	}
	return interceptor(ctx, in, info, handler)
}

var _CentralService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.CentralService",
	HandlerType: (*CentralServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushCheck",
			Handler:    _CentralService_PushCheck_Handler,
		},
		{
			MethodName: "RemoveCheck",
			Handler:    _CentralService_RemoveCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/central/proto/central.proto",
}
