// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// BoolResponse represents a boolean response where the action could either
// be successful or unsuccessful. If the action is not-successful, error is
// returned as the reason for the same.
type BoolResponse struct {
	Successful           bool     `protobuf:"varint,1,opt,name=Successful,proto3" json:"Successful,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BoolResponse) Reset()         { *m = BoolResponse{} }
func (m *BoolResponse) String() string { return proto.CompactTextString(m) }
func (*BoolResponse) ProtoMessage()    {}
func (*BoolResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

func (m *BoolResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoolResponse.Unmarshal(m, b)
}
func (m *BoolResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoolResponse.Marshal(b, m, deterministic)
}
func (m *BoolResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoolResponse.Merge(m, src)
}
func (m *BoolResponse) XXX_Size() int {
	return xxx_messageInfo_BoolResponse.Size(m)
}
func (m *BoolResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BoolResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BoolResponse proto.InternalMessageInfo

func (m *BoolResponse) GetSuccessful() bool {
	if m != nil {
		return m.Successful
	}
	return false
}

func (m *BoolResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

// Nil represents an nil message.
type Nil struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Nil) Reset()         { *m = Nil{} }
func (m *Nil) String() string { return proto.CompactTextString(m) }
func (*Nil) ProtoMessage()    {}
func (*Nil) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{1}
}

func (m *Nil) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nil.Unmarshal(m, b)
}
func (m *Nil) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nil.Marshal(b, m, deterministic)
}
func (m *Nil) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nil.Merge(m, src)
}
func (m *Nil) XXX_Size() int {
	return xxx_messageInfo_Nil.Size(m)
}
func (m *Nil) XXX_DiscardUnknown() {
	xxx_messageInfo_Nil.DiscardUnknown(m)
}

var xxx_messageInfo_Nil proto.InternalMessageInfo

// Check represents the configuration for a check that can be pushed to or
// removed from an agent.
type Check struct {
	ID                   string       `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string       `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Interval             int64        `protobuf:"varint,3,opt,name=Interval,proto3" json:"Interval,omitempty"`
	Timeout              int64        `protobuf:"varint,4,opt,name=Timeout,proto3" json:"Timeout,omitempty"`
	Input                *Component   `protobuf:"bytes,5,opt,name=Input,proto3" json:"Input,omitempty"`
	Output               *Component   `protobuf:"bytes,6,opt,name=Output,proto3" json:"Output,omitempty"`
	Target               *Component   `protobuf:"bytes,7,opt,name=Target,proto3" json:"Target,omitempty"`
	Payloads             []*Component `protobuf:"bytes,8,rep,name=Payloads,proto3" json:"Payloads,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Check) Reset()         { *m = Check{} }
func (m *Check) String() string { return proto.CompactTextString(m) }
func (*Check) ProtoMessage()    {}
func (*Check) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{2}
}

func (m *Check) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Check.Unmarshal(m, b)
}
func (m *Check) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Check.Marshal(b, m, deterministic)
}
func (m *Check) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Check.Merge(m, src)
}
func (m *Check) XXX_Size() int {
	return xxx_messageInfo_Check.Size(m)
}
func (m *Check) XXX_DiscardUnknown() {
	xxx_messageInfo_Check.DiscardUnknown(m)
}

var xxx_messageInfo_Check proto.InternalMessageInfo

func (m *Check) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Check) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Check) GetInterval() int64 {
	if m != nil {
		return m.Interval
	}
	return 0
}

func (m *Check) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *Check) GetInput() *Component {
	if m != nil {
		return m.Input
	}
	return nil
}

func (m *Check) GetOutput() *Component {
	if m != nil {
		return m.Output
	}
	return nil
}

func (m *Check) GetTarget() *Component {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *Check) GetPayloads() []*Component {
	if m != nil {
		return m.Payloads
	}
	return nil
}

// Component represents a key-value pair. This can be used for representing
// input, output, target etc. for a check.
type Component struct {
	Type                 string   `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Component) Reset()         { *m = Component{} }
func (m *Component) String() string { return proto.CompactTextString(m) }
func (*Component) ProtoMessage()    {}
func (*Component) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{3}
}

func (m *Component) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Component.Unmarshal(m, b)
}
func (m *Component) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Component.Marshal(b, m, deterministic)
}
func (m *Component) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Component.Merge(m, src)
}
func (m *Component) XXX_Size() int {
	return xxx_messageInfo_Component.Size(m)
}
func (m *Component) XXX_DiscardUnknown() {
	xxx_messageInfo_Component.DiscardUnknown(m)
}

var xxx_messageInfo_Component proto.InternalMessageInfo

func (m *Component) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Component) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// CheckID is the ID of the check on which the action will be invoked.
type CheckID struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckID) Reset()         { *m = CheckID{} }
func (m *CheckID) String() string { return proto.CompactTextString(m) }
func (*CheckID) ProtoMessage()    {}
func (*CheckID) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{4}
}

func (m *CheckID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckID.Unmarshal(m, b)
}
func (m *CheckID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckID.Marshal(b, m, deterministic)
}
func (m *CheckID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckID.Merge(m, src)
}
func (m *CheckID) XXX_Size() int {
	return xxx_messageInfo_CheckID.Size(m)
}
func (m *CheckID) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckID.DiscardUnknown(m)
}

var xxx_messageInfo_CheckID proto.InternalMessageInfo

func (m *CheckID) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

// CheckList is a list of multiple checks.
type CheckList struct {
	Checks               []*CheckID `protobuf:"bytes,1,rep,name=checks,proto3" json:"checks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CheckList) Reset()         { *m = CheckList{} }
func (m *CheckList) String() string { return proto.CompactTextString(m) }
func (*CheckList) ProtoMessage()    {}
func (*CheckList) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{5}
}

func (m *CheckList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckList.Unmarshal(m, b)
}
func (m *CheckList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckList.Marshal(b, m, deterministic)
}
func (m *CheckList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckList.Merge(m, src)
}
func (m *CheckList) XXX_Size() int {
	return xxx_messageInfo_CheckList.Size(m)
}
func (m *CheckList) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckList.DiscardUnknown(m)
}

var xxx_messageInfo_CheckList proto.InternalMessageInfo

func (m *CheckList) GetChecks() []*CheckID {
	if m != nil {
		return m.Checks
	}
	return nil
}

func init() {
	proto.RegisterType((*BoolResponse)(nil), "proto.BoolResponse")
	proto.RegisterType((*Nil)(nil), "proto.Nil")
	proto.RegisterType((*Check)(nil), "proto.Check")
	proto.RegisterType((*Component)(nil), "proto.Component")
	proto.RegisterType((*CheckID)(nil), "proto.CheckID")
	proto.RegisterType((*CheckList)(nil), "proto.CheckList")
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_4dc296cbfe5ffcd5) }

var fileDescriptor_4dc296cbfe5ffcd5 = []byte{
	// 318 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0x69, 0xbb, 0x76, 0xed, 0x53, 0x86, 0x04, 0x0f, 0xd1, 0x83, 0x94, 0x1e, 0xa4, 0x07,
	0xa9, 0xe0, 0xf0, 0x0b, 0x6c, 0xf5, 0x50, 0x90, 0x29, 0x71, 0x78, 0xf0, 0x16, 0xeb, 0x73, 0x0e,
	0xdb, 0xa6, 0x34, 0xa9, 0xb0, 0xcf, 0xe0, 0x97, 0x96, 0x24, 0x5d, 0x11, 0x71, 0xa7, 0xe4, 0x9f,
	0xdf, 0xff, 0xc1, 0xcb, 0x0f, 0x66, 0x35, 0x4a, 0xc9, 0x37, 0x28, 0xb3, 0xb6, 0x13, 0x4a, 0x10,
	0xdf, 0x1c, 0x49, 0x0e, 0xc7, 0x0b, 0x21, 0x2a, 0x86, 0xb2, 0x15, 0x8d, 0x44, 0x72, 0x01, 0xf0,
	0xd4, 0x97, 0x25, 0x4a, 0xf9, 0xde, 0x57, 0xd4, 0x89, 0x9d, 0x34, 0x64, 0xbf, 0x5e, 0xc8, 0x29,
	0xf8, 0x77, 0x5d, 0x27, 0x3a, 0xea, 0xc6, 0x4e, 0x1a, 0x31, 0x1b, 0x12, 0x1f, 0xbc, 0xd5, 0xb6,
	0x4a, 0xbe, 0x5d, 0xf0, 0x97, 0x1f, 0x58, 0x7e, 0x92, 0x19, 0xb8, 0x45, 0x6e, 0xc6, 0x23, 0xe6,
	0x16, 0x39, 0x21, 0x30, 0x59, 0xf1, 0x1a, 0x87, 0x29, 0x73, 0x27, 0xe7, 0x10, 0x16, 0x8d, 0xc2,
	0xee, 0x8b, 0x57, 0xd4, 0x8b, 0x9d, 0xd4, 0x63, 0x63, 0x26, 0x14, 0xa6, 0xeb, 0x6d, 0x8d, 0xa2,
	0x57, 0x74, 0x62, 0xd0, 0x3e, 0x92, 0x4b, 0xf0, 0x8b, 0xa6, 0xed, 0x15, 0xf5, 0x63, 0x27, 0x3d,
	0xba, 0x39, 0xb1, 0xdf, 0xc9, 0x96, 0xa2, 0x6e, 0x45, 0x83, 0x8d, 0x62, 0x16, 0x93, 0x14, 0x82,
	0x87, 0x5e, 0xe9, 0x62, 0x70, 0xa0, 0x38, 0x70, 0xdd, 0x5c, 0xf3, 0x6e, 0x83, 0x8a, 0x4e, 0x0f,
	0x35, 0x2d, 0x27, 0x57, 0x10, 0x3e, 0xf2, 0x5d, 0x25, 0xf8, 0x9b, 0xa4, 0x61, 0xec, 0xfd, 0xdb,
	0x1d, 0x1b, 0xc9, 0x2d, 0x44, 0xe3, 0xb3, 0x16, 0xb0, 0xde, 0xb5, 0x38, 0x28, 0x31, 0x77, 0xed,
	0xf2, 0x99, 0x57, 0xfd, 0xde, 0x8a, 0x0d, 0xc9, 0x19, 0x4c, 0x8d, 0xc3, 0x22, 0xff, 0x6b, 0x31,
	0x99, 0x43, 0x64, 0xd0, 0xfd, 0x56, 0x6a, 0x11, 0x41, 0xa9, 0x83, 0xa4, 0x8e, 0x59, 0x65, 0xb6,
	0x5f, 0xc5, 0x0e, 0xb3, 0x81, 0x2e, 0xe0, 0x25, 0xcc, 0xb2, 0x6b, 0xc3, 0x5e, 0x03, 0x73, 0xcc,
	0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xab, 0x14, 0xf7, 0xd0, 0x0d, 0x02, 0x00, 0x00,
}
