// Code generated by protoc-gen-go. DO NOT EDIT.
// source: agent.proto

package agent

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Metadata for a Check.
type Check struct {
	Input    string            `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	Target   string            `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Output   string            `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	Payloads []*Check_Payloads `protobuf:"bytes,4,rep,name=payloads,proto3" json:"payloads,omitempty"`
	// Both the interval and the timeout values are in
	// seconds.
	Interval             int64    `protobuf:"varint,5,opt,name=interval,proto3" json:"interval,omitempty"`
	Timeout              int64    `protobuf:"varint,6,opt,name=timeout,proto3" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Check) Reset()         { *m = Check{} }
func (m *Check) String() string { return proto.CompactTextString(m) }
func (*Check) ProtoMessage()    {}
func (*Check) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{0}
}

func (m *Check) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Check.Unmarshal(m, b)
}
func (m *Check) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Check.Marshal(b, m, deterministic)
}
func (m *Check) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Check.Merge(m, src)
}
func (m *Check) XXX_Size() int {
	return xxx_messageInfo_Check.Size(m)
}
func (m *Check) XXX_DiscardUnknown() {
	xxx_messageInfo_Check.DiscardUnknown(m)
}

var xxx_messageInfo_Check proto.InternalMessageInfo

func (m *Check) GetInput() string {
	if m != nil {
		return m.Input
	}
	return ""
}

func (m *Check) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *Check) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

func (m *Check) GetPayloads() []*Check_Payloads {
	if m != nil {
		return m.Payloads
	}
	return nil
}

func (m *Check) GetInterval() int64 {
	if m != nil {
		return m.Interval
	}
	return 0
}

func (m *Check) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

type Check_Payloads struct {
	PayloadType          string   `protobuf:"bytes,1,opt,name=payload_type,json=payloadType,proto3" json:"payload_type,omitempty"`
	Payload              string   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Check_Payloads) Reset()         { *m = Check_Payloads{} }
func (m *Check_Payloads) String() string { return proto.CompactTextString(m) }
func (*Check_Payloads) ProtoMessage()    {}
func (*Check_Payloads) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{0, 0}
}

func (m *Check_Payloads) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Check_Payloads.Unmarshal(m, b)
}
func (m *Check_Payloads) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Check_Payloads.Marshal(b, m, deterministic)
}
func (m *Check_Payloads) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Check_Payloads.Merge(m, src)
}
func (m *Check_Payloads) XXX_Size() int {
	return xxx_messageInfo_Check_Payloads.Size(m)
}
func (m *Check_Payloads) XXX_DiscardUnknown() {
	xxx_messageInfo_Check_Payloads.DiscardUnknown(m)
}

var xxx_messageInfo_Check_Payloads proto.InternalMessageInfo

func (m *Check_Payloads) GetPayloadType() string {
	if m != nil {
		return m.PayloadType
	}
	return ""
}

func (m *Check_Payloads) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

// This is the data structure storing the stats returned by
// Manager.
type ManagerStats struct {
	ControllerStatus     []*ManagerStats_ControllerStatus `protobuf:"bytes,1,rep,name=controller_status,json=controllerStatus,proto3" json:"controller_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *ManagerStats) Reset()         { *m = ManagerStats{} }
func (m *ManagerStats) String() string { return proto.CompactTextString(m) }
func (*ManagerStats) ProtoMessage()    {}
func (*ManagerStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{1}
}

func (m *ManagerStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManagerStats.Unmarshal(m, b)
}
func (m *ManagerStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManagerStats.Marshal(b, m, deterministic)
}
func (m *ManagerStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManagerStats.Merge(m, src)
}
func (m *ManagerStats) XXX_Size() int {
	return xxx_messageInfo_ManagerStats.Size(m)
}
func (m *ManagerStats) XXX_DiscardUnknown() {
	xxx_messageInfo_ManagerStats.DiscardUnknown(m)
}

var xxx_messageInfo_ManagerStats proto.InternalMessageInfo

func (m *ManagerStats) GetControllerStatus() []*ManagerStats_ControllerStatus {
	if m != nil {
		return m.ControllerStatus
	}
	return nil
}

type ManagerStats_ControllerConfigurationStatus struct {
	ErrorRetry           bool     `protobuf:"varint,1,opt,name=error_retry,json=errorRetry,proto3" json:"error_retry,omitempty"`
	ShouldBackOff        bool     `protobuf:"varint,2,opt,name=should_back_off,json=shouldBackOff,proto3" json:"should_back_off,omitempty"`
	Interval             string   `protobuf:"bytes,3,opt,name=interval,proto3" json:"interval,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ManagerStats_ControllerConfigurationStatus) Reset() {
	*m = ManagerStats_ControllerConfigurationStatus{}
}
func (m *ManagerStats_ControllerConfigurationStatus) String() string {
	return proto.CompactTextString(m)
}
func (*ManagerStats_ControllerConfigurationStatus) ProtoMessage() {}
func (*ManagerStats_ControllerConfigurationStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{1, 0}
}

func (m *ManagerStats_ControllerConfigurationStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManagerStats_ControllerConfigurationStatus.Unmarshal(m, b)
}
func (m *ManagerStats_ControllerConfigurationStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManagerStats_ControllerConfigurationStatus.Marshal(b, m, deterministic)
}
func (m *ManagerStats_ControllerConfigurationStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManagerStats_ControllerConfigurationStatus.Merge(m, src)
}
func (m *ManagerStats_ControllerConfigurationStatus) XXX_Size() int {
	return xxx_messageInfo_ManagerStats_ControllerConfigurationStatus.Size(m)
}
func (m *ManagerStats_ControllerConfigurationStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ManagerStats_ControllerConfigurationStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ManagerStats_ControllerConfigurationStatus proto.InternalMessageInfo

func (m *ManagerStats_ControllerConfigurationStatus) GetErrorRetry() bool {
	if m != nil {
		return m.ErrorRetry
	}
	return false
}

func (m *ManagerStats_ControllerConfigurationStatus) GetShouldBackOff() bool {
	if m != nil {
		return m.ShouldBackOff
	}
	return false
}

func (m *ManagerStats_ControllerConfigurationStatus) GetInterval() string {
	if m != nil {
		return m.Interval
	}
	return ""
}

type ManagerStats_ControllerRunStatus struct {
	SuccessCount         int64    `protobuf:"varint,1,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	FailureCount         int64    `protobuf:"varint,2,opt,name=failure_count,json=failureCount,proto3" json:"failure_count,omitempty"`
	ConsecFailureCount   int64    `protobuf:"varint,3,opt,name=consec_failure_count,json=consecFailureCount,proto3" json:"consec_failure_count,omitempty"`
	LastSuccessTime      string   `protobuf:"bytes,4,opt,name=last_success_time,json=lastSuccessTime,proto3" json:"last_success_time,omitempty"`
	LastFailureTime      string   `protobuf:"bytes,5,opt,name=last_failure_time,json=lastFailureTime,proto3" json:"last_failure_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ManagerStats_ControllerRunStatus) Reset()         { *m = ManagerStats_ControllerRunStatus{} }
func (m *ManagerStats_ControllerRunStatus) String() string { return proto.CompactTextString(m) }
func (*ManagerStats_ControllerRunStatus) ProtoMessage()    {}
func (*ManagerStats_ControllerRunStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{1, 1}
}

func (m *ManagerStats_ControllerRunStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManagerStats_ControllerRunStatus.Unmarshal(m, b)
}
func (m *ManagerStats_ControllerRunStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManagerStats_ControllerRunStatus.Marshal(b, m, deterministic)
}
func (m *ManagerStats_ControllerRunStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManagerStats_ControllerRunStatus.Merge(m, src)
}
func (m *ManagerStats_ControllerRunStatus) XXX_Size() int {
	return xxx_messageInfo_ManagerStats_ControllerRunStatus.Size(m)
}
func (m *ManagerStats_ControllerRunStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ManagerStats_ControllerRunStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ManagerStats_ControllerRunStatus proto.InternalMessageInfo

func (m *ManagerStats_ControllerRunStatus) GetSuccessCount() int64 {
	if m != nil {
		return m.SuccessCount
	}
	return 0
}

func (m *ManagerStats_ControllerRunStatus) GetFailureCount() int64 {
	if m != nil {
		return m.FailureCount
	}
	return 0
}

func (m *ManagerStats_ControllerRunStatus) GetConsecFailureCount() int64 {
	if m != nil {
		return m.ConsecFailureCount
	}
	return 0
}

func (m *ManagerStats_ControllerRunStatus) GetLastSuccessTime() string {
	if m != nil {
		return m.LastSuccessTime
	}
	return ""
}

func (m *ManagerStats_ControllerRunStatus) GetLastFailureTime() string {
	if m != nil {
		return m.LastFailureTime
	}
	return ""
}

type ManagerStats_ControllerStatus struct {
	Name                 string                                      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ConfigStatus         *ManagerStats_ControllerConfigurationStatus `protobuf:"bytes,2,opt,name=config_status,json=configStatus,proto3" json:"config_status,omitempty"`
	RunStatus            *ManagerStats_ControllerRunStatus           `protobuf:"bytes,3,opt,name=run_status,json=runStatus,proto3" json:"run_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                    `json:"-"`
	XXX_unrecognized     []byte                                      `json:"-"`
	XXX_sizecache        int32                                       `json:"-"`
}

func (m *ManagerStats_ControllerStatus) Reset()         { *m = ManagerStats_ControllerStatus{} }
func (m *ManagerStats_ControllerStatus) String() string { return proto.CompactTextString(m) }
func (*ManagerStats_ControllerStatus) ProtoMessage()    {}
func (*ManagerStats_ControllerStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{1, 2}
}

func (m *ManagerStats_ControllerStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManagerStats_ControllerStatus.Unmarshal(m, b)
}
func (m *ManagerStats_ControllerStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManagerStats_ControllerStatus.Marshal(b, m, deterministic)
}
func (m *ManagerStats_ControllerStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManagerStats_ControllerStatus.Merge(m, src)
}
func (m *ManagerStats_ControllerStatus) XXX_Size() int {
	return xxx_messageInfo_ManagerStats_ControllerStatus.Size(m)
}
func (m *ManagerStats_ControllerStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ManagerStats_ControllerStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ManagerStats_ControllerStatus proto.InternalMessageInfo

func (m *ManagerStats_ControllerStatus) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ManagerStats_ControllerStatus) GetConfigStatus() *ManagerStats_ControllerConfigurationStatus {
	if m != nil {
		return m.ConfigStatus
	}
	return nil
}

func (m *ManagerStats_ControllerStatus) GetRunStatus() *ManagerStats_ControllerRunStatus {
	if m != nil {
		return m.RunStatus
	}
	return nil
}

// This is to check if the pushed check is consumed by the agent
// or not.
type PushStatus struct {
	Pushed               bool     `protobuf:"varint,1,opt,name=Pushed,proto3" json:"Pushed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushStatus) Reset()         { *m = PushStatus{} }
func (m *PushStatus) String() string { return proto.CompactTextString(m) }
func (*PushStatus) ProtoMessage()    {}
func (*PushStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{2}
}

func (m *PushStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushStatus.Unmarshal(m, b)
}
func (m *PushStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushStatus.Marshal(b, m, deterministic)
}
func (m *PushStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushStatus.Merge(m, src)
}
func (m *PushStatus) XXX_Size() int {
	return xxx_messageInfo_PushStatus.Size(m)
}
func (m *PushStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_PushStatus.DiscardUnknown(m)
}

var xxx_messageInfo_PushStatus proto.InternalMessageInfo

func (m *PushStatus) GetPushed() bool {
	if m != nil {
		return m.Pushed
	}
	return false
}

type None struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *None) Reset()         { *m = None{} }
func (m *None) String() string { return proto.CompactTextString(m) }
func (*None) ProtoMessage()    {}
func (*None) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{3}
}

func (m *None) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_None.Unmarshal(m, b)
}
func (m *None) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_None.Marshal(b, m, deterministic)
}
func (m *None) XXX_Merge(src proto.Message) {
	xxx_messageInfo_None.Merge(m, src)
}
func (m *None) XXX_Size() int {
	return xxx_messageInfo_None.Size(m)
}
func (m *None) XXX_DiscardUnknown() {
	xxx_messageInfo_None.DiscardUnknown(m)
}

var xxx_messageInfo_None proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Check)(nil), "agent.Check")
	proto.RegisterType((*Check_Payloads)(nil), "agent.Check.Payloads")
	proto.RegisterType((*ManagerStats)(nil), "agent.ManagerStats")
	proto.RegisterType((*ManagerStats_ControllerConfigurationStatus)(nil), "agent.ManagerStats.ControllerConfigurationStatus")
	proto.RegisterType((*ManagerStats_ControllerRunStatus)(nil), "agent.ManagerStats.ControllerRunStatus")
	proto.RegisterType((*ManagerStats_ControllerStatus)(nil), "agent.ManagerStats.ControllerStatus")
	proto.RegisterType((*PushStatus)(nil), "agent.PushStatus")
	proto.RegisterType((*None)(nil), "agent.None")
}

func init() { proto.RegisterFile("agent.proto", fileDescriptor_56ede974c0020f77) }

var fileDescriptor_56ede974c0020f77 = []byte{
	// 556 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x94, 0xdf, 0x6e, 0xd3, 0x3c,
	0x18, 0xc6, 0x97, 0xa5, 0xe9, 0xd7, 0xbd, 0xc9, 0xb4, 0xd5, 0xdb, 0x37, 0x45, 0x91, 0x10, 0x25,
	0x4c, 0x50, 0x71, 0x50, 0xb1, 0x22, 0x2e, 0x00, 0x2a, 0x6d, 0x47, 0xc0, 0x48, 0x27, 0x4e, 0x23,
	0xcf, 0x75, 0xda, 0xa8, 0xa9, 0x5d, 0x39, 0xf6, 0xa4, 0x9e, 0x73, 0x1b, 0xdc, 0x0e, 0xf7, 0xc2,
	0x55, 0x80, 0xfc, 0x27, 0x69, 0x3b, 0x4d, 0x3b, 0xf3, 0xf3, 0xf8, 0xd7, 0xe7, 0xf5, 0xdb, 0xd7,
	0x0e, 0x84, 0x78, 0x4e, 0x99, 0x1c, 0xad, 0x05, 0x97, 0x1c, 0x05, 0x46, 0xa4, 0x7f, 0x3d, 0x08,
	0x26, 0x0b, 0x4a, 0x96, 0xe8, 0x1c, 0x82, 0x92, 0xad, 0x95, 0x8c, 0xbd, 0x81, 0x37, 0x3c, 0xca,
	0xac, 0x40, 0x17, 0xd0, 0x95, 0x58, 0xcc, 0xa9, 0x8c, 0x0f, 0x8d, 0xed, 0x94, 0xf6, 0xb9, 0x92,
	0x1a, 0xf7, 0xad, 0x6f, 0x15, 0xba, 0x82, 0xde, 0x1a, 0x6f, 0x2a, 0x8e, 0x67, 0x75, 0xdc, 0x19,
	0xf8, 0xc3, 0x70, 0xfc, 0xff, 0xc8, 0x96, 0x35, 0x55, 0x46, 0xb7, 0x6e, 0x33, 0x6b, 0x31, 0x94,
	0x40, 0xaf, 0x64, 0x92, 0x8a, 0x07, 0x5c, 0xc5, 0xc1, 0xc0, 0x1b, 0xfa, 0x59, 0xab, 0x51, 0x0c,
	0xff, 0xc9, 0x72, 0x45, 0xb9, 0x92, 0x71, 0xd7, 0x6c, 0x35, 0x32, 0xb9, 0x81, 0x5e, 0x93, 0x85,
	0x5e, 0x41, 0xe4, 0xd2, 0x72, 0xb9, 0x59, 0x53, 0xd7, 0x41, 0xe8, 0xbc, 0xbb, 0xcd, 0x9a, 0xea,
	0x20, 0x27, 0x5d, 0x23, 0x8d, 0x4c, 0x7f, 0x05, 0x10, 0x7d, 0xc1, 0x0c, 0xcf, 0xa9, 0x98, 0x4a,
	0x2c, 0x6b, 0xf4, 0x1d, 0xfa, 0x84, 0x33, 0x29, 0x78, 0x55, 0x51, 0x91, 0xd7, 0x12, 0x4b, 0x55,
	0xc7, 0x9e, 0xe9, 0xe5, 0xd2, 0xf5, 0xb2, 0xcb, 0x8f, 0x26, 0x2d, 0x3c, 0x35, 0x6c, 0x76, 0x4a,
	0x1e, 0x39, 0xc9, 0x4f, 0x0f, 0x5e, 0x6c, 0xb1, 0x09, 0x67, 0x45, 0x39, 0x57, 0x02, 0xcb, 0x92,
	0x33, 0x4b, 0xa0, 0x97, 0x10, 0x52, 0x21, 0xb8, 0xc8, 0x05, 0x95, 0x62, 0x63, 0x3a, 0xe8, 0x65,
	0x60, 0xac, 0x4c, 0x3b, 0xe8, 0x0d, 0x9c, 0xd4, 0x0b, 0xae, 0xaa, 0x59, 0x7e, 0x8f, 0xc9, 0x32,
	0xe7, 0x45, 0x61, 0x1a, 0xe9, 0x65, 0xc7, 0xd6, 0xfe, 0x8c, 0xc9, 0xf2, 0x5b, 0x51, 0xec, 0xfd,
	0x9b, 0x76, 0x34, 0xad, 0x4e, 0xfe, 0x78, 0x70, 0xb6, 0x3d, 0x46, 0xa6, 0x9a, 0xe2, 0xaf, 0xe1,
	0xb8, 0x56, 0x84, 0xd0, 0xba, 0xce, 0x09, 0x57, 0xcc, 0x5e, 0x01, 0x3f, 0x8b, 0x9c, 0x39, 0xd1,
	0x9e, 0x86, 0x0a, 0x5c, 0x56, 0x4a, 0x50, 0x07, 0x1d, 0x5a, 0xc8, 0x99, 0x16, 0x7a, 0x0f, 0xe7,
	0x84, 0xb3, 0x9a, 0x92, 0x7c, 0x9f, 0xf5, 0x0d, 0x8b, 0xec, 0xde, 0xf5, 0xee, 0x2f, 0xde, 0x41,
	0xbf, 0xc2, 0xb5, 0xcc, 0x9b, 0x03, 0xe8, 0xf9, 0xc6, 0x1d, 0x73, 0xf0, 0x13, 0xbd, 0x31, 0xb5,
	0xfe, 0x5d, 0xb9, 0xa2, 0x2d, 0xdb, 0x64, 0x1b, 0x36, 0xd8, 0xb2, 0x2e, 0x58, 0xb3, 0xc9, 0x6f,
	0x0f, 0x4e, 0x1f, 0x4f, 0x06, 0x21, 0xe8, 0x30, 0xbc, 0x6a, 0x2e, 0x88, 0x59, 0xa3, 0x1f, 0x70,
	0x4c, 0xcc, 0x40, 0x9a, 0x51, 0xeb, 0xbe, 0xc2, 0xf1, 0xd5, 0xf3, 0xa3, 0x7e, 0x62, 0x86, 0x59,
	0x64, 0x73, 0x5c, 0xad, 0x6b, 0x00, 0xa1, 0x58, 0x13, 0xea, 0x9b, 0xd0, 0xb7, 0xcf, 0x87, 0xb6,
	0x13, 0xc9, 0x8e, 0x44, 0xb3, 0x4c, 0x2f, 0x01, 0x6e, 0x55, 0xbd, 0x70, 0xa9, 0x17, 0xd0, 0xd5,
	0x8a, 0xce, 0xdc, 0x15, 0x71, 0x2a, 0xed, 0x42, 0xe7, 0x2b, 0x67, 0x74, 0xac, 0x20, 0xfa, 0xa4,
	0x4b, 0x4c, 0xa9, 0x78, 0x28, 0x09, 0x45, 0x23, 0x38, 0xd2, 0x84, 0x7d, 0xe2, 0xd1, 0xee, 0x53,
	0x4c, 0xfa, 0x4e, 0x6d, 0xd3, 0xd3, 0x03, 0xf4, 0x11, 0x4e, 0x6e, 0xa8, 0xdc, 0x7b, 0x0f, 0xa1,
	0xe3, 0x74, 0x7e, 0x72, 0xf6, 0x44, 0x07, 0xe9, 0xc1, 0x7d, 0xd7, 0x7c, 0x54, 0x3e, 0xfc, 0x0b,
	0x00, 0x00, 0xff, 0xff, 0x82, 0x0a, 0x4c, 0xff, 0x63, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AgentServiceClient interface {
	// Pushes a check to the agent service to be processed and managed
	PushCheck(ctx context.Context, in *Check, opts ...grpc.CallOption) (*PushStatus, error)
	// Returns the status of manager managing the controllers corresponding to
	// the checks.
	GetManagerStats(ctx context.Context, in *None, opts ...grpc.CallOption) (*ManagerStats, error)
}

type agentServiceClient struct {
	cc *grpc.ClientConn
}

func NewAgentServiceClient(cc *grpc.ClientConn) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) PushCheck(ctx context.Context, in *Check, opts ...grpc.CallOption) (*PushStatus, error) {
	out := new(PushStatus)
	err := c.cc.Invoke(ctx, "/agent.AgentService/PushCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetManagerStats(ctx context.Context, in *None, opts ...grpc.CallOption) (*ManagerStats, error) {
	out := new(ManagerStats)
	err := c.cc.Invoke(ctx, "/agent.AgentService/GetManagerStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
type AgentServiceServer interface {
	// Pushes a check to the agent service to be processed and managed
	PushCheck(context.Context, *Check) (*PushStatus, error)
	// Returns the status of manager managing the controllers corresponding to
	// the checks.
	GetManagerStats(context.Context, *None) (*ManagerStats, error)
}

// UnimplementedAgentServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAgentServiceServer struct {
}

func (*UnimplementedAgentServiceServer) PushCheck(ctx context.Context, req *Check) (*PushStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushCheck not implemented")
}
func (*UnimplementedAgentServiceServer) GetManagerStats(ctx context.Context, req *None) (*ManagerStats, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetManagerStats not implemented")
}

func RegisterAgentServiceServer(s *grpc.Server, srv AgentServiceServer) {
	s.RegisterService(&_AgentService_serviceDesc, srv)
}

func _AgentService_PushCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Check)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).PushCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.AgentService/PushCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).PushCheck(ctx, req.(*Check))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetManagerStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(None)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetManagerStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.AgentService/GetManagerStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetManagerStats(ctx, req.(*None))
	}
	return interceptor(ctx, in, info, handler)
}

var _AgentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "agent.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushCheck",
			Handler:    _AgentService_PushCheck_Handler,
		},
		{
			MethodName: "GetManagerStats",
			Handler:    _AgentService_GetManagerStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent.proto",
}
