title: Pinger
email: contact@sdslabs.co.in
description: >-
  An open-source implementation of an application that can create status pages.
baseurl: ""

markdown: kramdown
kramdown:
  highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

theme: just-the-docs
remote_theme: pmarsceill/just-the-docs
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag

defaults:
-
  scope:
    path: ""
  values:
    layout: default

color_scheme: pinger

search_enabled: true
search:
  heading_level: 3
  button: true

aux_links_new_tab: true
aux_links:
  "Source code on Github":
    - "//github.com/sdslabs/pinger"

footer_content: >-
  Copyright &copy; 2020 <a href="//sdslabs.co" target="_blank">SDSLabs</a>.
  Distributed by an
  <a href="//github.com/sdslabs/pinger/tree/main/LICENSE" target="_blank">
    MIT license
  </a>.

last_edit_timestamp: true
last_edit_time_format: "%d %B, %Y at %I:%M %p"

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "//github.com/sdslabs/pinger"
gh_edit_branch: "main/docs"
gh_edit_view_mode: "edit"

exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- README.md
- .git/
- .gitignore
- .github/
