// Code generated by protoc-gen-go. DO NOT EDIT.
// source: central.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("central.proto", fileDescriptor_7ee0acf6e5b6c9a2) }

var fileDescriptor_7ee0acf6e5b6c9a2 = []byte{
	// 150 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x4e, 0xcd, 0x2b,
	0x29, 0x4a, 0xcc, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x52, 0x7c, 0xb9,
	0xa9, 0xc5, 0xc5, 0x89, 0xe9, 0xa9, 0xc5, 0x10, 0x61, 0xa3, 0xf9, 0x8c, 0x5c, 0xec, 0xce, 0x10,
	0x85, 0x42, 0x3a, 0x5c, 0x5c, 0x3e, 0x99, 0xc5, 0x25, 0xce, 0x19, 0xa9, 0xc9, 0xd9, 0xc5, 0x42,
	0x5c, 0x10, 0x15, 0x7a, 0x7e, 0x99, 0x39, 0x52, 0x02, 0x50, 0x36, 0x58, 0x0a, 0xa4, 0x46, 0x89,
	0x41, 0xc8, 0x80, 0x8b, 0x33, 0xa0, 0xb4, 0x38, 0x03, 0x2c, 0x24, 0xc4, 0x83, 0xac, 0x40, 0x4a,
	0x18, 0xca, 0x73, 0xca, 0xcf, 0xcf, 0x09, 0x4a, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x55, 0x62,
	0x10, 0x32, 0xe1, 0xe2, 0x0e, 0x4a, 0xcd, 0xcd, 0x2f, 0x4b, 0x85, 0xe8, 0xe1, 0x43, 0xd6, 0xe3,
	0xe9, 0x82, 0x43, 0x57, 0x12, 0x1b, 0x58, 0xd4, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x13, 0x13,
	0x18, 0xbd, 0xd0, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CentralClient is the client API for Central service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CentralClient interface {
	// ListChecks fetches a list of checks registered.
	ListChecks(ctx context.Context, in *Nil, opts ...grpc.CallOption) (*CheckList, error)
	// PushCheck creates a new check. If the check already exists it simply
	// updates the check.
	PushCheck(ctx context.Context, in *Check, opts ...grpc.CallOption) (*BoolResponse, error)
	// RemoveCheck removes the check.
	RemoveCheck(ctx context.Context, in *CheckID, opts ...grpc.CallOption) (*BoolResponse, error)
}

type centralClient struct {
	cc grpc.ClientConnInterface
}

func NewCentralClient(cc grpc.ClientConnInterface) CentralClient {
	return &centralClient{cc}
}

func (c *centralClient) ListChecks(ctx context.Context, in *Nil, opts ...grpc.CallOption) (*CheckList, error) {
	out := new(CheckList)
	err := c.cc.Invoke(ctx, "/proto.Central/ListChecks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *centralClient) PushCheck(ctx context.Context, in *Check, opts ...grpc.CallOption) (*BoolResponse, error) {
	out := new(BoolResponse)
	err := c.cc.Invoke(ctx, "/proto.Central/PushCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *centralClient) RemoveCheck(ctx context.Context, in *CheckID, opts ...grpc.CallOption) (*BoolResponse, error) {
	out := new(BoolResponse)
	err := c.cc.Invoke(ctx, "/proto.Central/RemoveCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CentralServer is the server API for Central service.
type CentralServer interface {
	// ListChecks fetches a list of checks registered.
	ListChecks(context.Context, *Nil) (*CheckList, error)
	// PushCheck creates a new check. If the check already exists it simply
	// updates the check.
	PushCheck(context.Context, *Check) (*BoolResponse, error)
	// RemoveCheck removes the check.
	RemoveCheck(context.Context, *CheckID) (*BoolResponse, error)
}

// UnimplementedCentralServer can be embedded to have forward compatible implementations.
type UnimplementedCentralServer struct {
}

func (*UnimplementedCentralServer) ListChecks(ctx context.Context, req *Nil) (*CheckList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListChecks not implemented")
}
func (*UnimplementedCentralServer) PushCheck(ctx context.Context, req *Check) (*BoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushCheck not implemented")
}
func (*UnimplementedCentralServer) RemoveCheck(ctx context.Context, req *CheckID) (*BoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveCheck not implemented")
}

func RegisterCentralServer(s *grpc.Server, srv CentralServer) {
	s.RegisterService(&_Central_serviceDesc, srv)
}

func _Central_ListChecks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Nil)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CentralServer).ListChecks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Central/ListChecks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CentralServer).ListChecks(ctx, req.(*Nil))
	}
	return interceptor(ctx, in, info, handler)
}

func _Central_PushCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Check)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CentralServer).PushCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Central/PushCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CentralServer).PushCheck(ctx, req.(*Check))
	}
	return interceptor(ctx, in, info, handler)
}

func _Central_RemoveCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CentralServer).RemoveCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Central/RemoveCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CentralServer).RemoveCheck(ctx, req.(*CheckID))
	}
	return interceptor(ctx, in, info, handler)
}

var _Central_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Central",
	HandlerType: (*CentralServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListChecks",
			Handler:    _Central_ListChecks_Handler,
		},
		{
			MethodName: "PushCheck",
			Handler:    _Central_PushCheck_Handler,
		},
		{
			MethodName: "RemoveCheck",
			Handler:    _Central_RemoveCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "central.proto",
}
