name: CD

on:
  push:
    branches: [ main ]

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: '0.4.4'

    - name: Check out code into the repository root
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Build
      run: make docs

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/book
