name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the repository root
      uses: actions/checkout@v2

    - name: Build
      run: make build

  lint:
    name: Lint
    runs-on: ubuntu-18.04
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the repository root
      uses: actions/checkout@v2

    - name: Setup tools (golangci-lint)
      run: >-
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh |
        sh -s -- -b $(go env GOPATH)/bin v1.32.2

    - name: Lint
      run: PATH="$(go env GOPATH)/bin:$PATH" make lint

  docs:
    name: Documentation
    runs-on: ubuntu-18.04
    steps:
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6

    - name: Check out code into the repository root
      uses: actions/checkout@v2

    - name: Build
      run: make docs

  docker:
    name: Docker Image
    runs-on: ubuntu-18.04
    steps:
    - name: Check out code into the repository root
      uses: actions/checkout@v2

    - name: Build
      run: make docker TAG="pinger:dev"

    - name: Run container
      run: docker run --rm pinger:dev
