name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - name: Check out code into the repository root
      uses: actions/checkout@v2

    - name: Generate static resources blob
      run: make static

    - name: Build
      run: make build

  lint:
    name: Lint
    runs-on: ubuntu-18.04
    steps:
    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - name: Check out code into the repository root
      uses: actions/checkout@v2

    - name: Setup tools (golangci-lint)
      run: >-
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh |
        sh -s -- -b $(go env GOPATH)/bin v1.32.2

    - name: Lint
      run: PATH="$(go env GOPATH)/bin:$PATH" make lint

  docs:
    name: Documentation
    runs-on: ubuntu-18.04
    steps:
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.4'

      - name: Check out code into the repository root
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Build
        run: make docs

  docker:
    name: Docker Image
    runs-on: ubuntu-18.04
    steps:
    - name: Check out code into the repository root
      uses: actions/checkout@v2

    - name: Build
      run: make docker TAG="pinger:dev"

    - name: Run container
      run: docker run --rm pinger:dev

  proto:
    name: Protobuf
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.14.0'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install proto-gen-go and proto-gen-go-grpc
        run: |
          export GO111MODULE=on
          go get google.golang.org/protobuf/cmd/protoc-gen-go@v1.25.0
          go get google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.0.1

      - name: Check out code into the repository root
        uses: actions/checkout@v2

      - name: Generate proto
        run: PATH="$(go env GOPATH)/bin:$PATH" make proto

      - name: Check diff
        run: ./build/diff.sh

  vendor:
    name: Vendor
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go

      - name: Check out code into the repository root
        uses: actions/checkout@v2

      - name: Update vendor
        run: make vendor

      - name: Check diff
        run: ./build/diff.sh
