name: Go CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - name: Check out code into the repository root
        uses: actions/checkout@v2

      - name: Build
        run: make build

  lint:
    name: Lint
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - name: Check out code into the repository root
        uses: actions/checkout@v2

      - name: Setup tools (golangci-lint)
        run: make install-golangcilint

      - name: Lint
        run: make lint
